### ISSUE TITLE
Docu missing on single SQL command limitation?

### ISSUE THREAD

**Issue by zaucker** [raku-community-modules/DBIish#133]
I couldn't find it in the docu, but I believe that there can be only one SQL statement handle by `dbh->do()` or per `sth->execute()`. Seems to be mostly a DB limitation/feature, but it would be good to mention here somewhere.

**Comment by jonathanstowe** [comment]
Hey it's Hacktober feel free to suggest the appropriate change :)

**Comment by zaucker** [comment]
The problem is that I don't really know what to say. Turns out that multiple statements do work with PostgreSQL and SQLite:
```
use v6;
use DBIish;

my $dbh = DBIish.connect('SQLite', database => './test-hash.sqlite3');
my $sth;

my $sql1 = q:to/SQL/;
    CREATE TABLE IF NOT EXISTS t1(id INTEGER, name TEXT);
    INSERT INTO t1 VALUES(1, 'Test1');
    SQL
my $sql2 = 'SELECT * FROM t1';
    
$dbh.do($sql1);
$sth = $dbh.prepare($sql2);
$sth.execute;
my @row = $sth.row;
dd @row;

$dbh = PROCESS::<$EASII-DB-CONNECTION> = DBIish.connect(
    'Pg', :host<localhost>, :port(5432), :database<test>, :user<postgres>, :password('')
);
$dbh.do($sql1);
$sth = $dbh.prepare($sql2);
$sth.execute;
@row = $sth.row;
dd @row;

$sth.finish;
$dbh.dispose;
```
gives
```console
perl6 multicmd.p6
Array @row = [1, "Test11"]
Array @row = [1, "Test1"]
```
On the other hand, all the docu on Perl5 DBI and DBD::Pg state that `do()` is supposed to be used with a single statement only, where as DBD::SQLite allows multiple statement if the appropriate flag is set.

There are many posts, e.g. on Perl monks, that don't recommend using multiple statements.

So I am bit at loss to decide what is right and what is wrong. In a way it seems that DBIish::do() better should not support multiple statements and either raise an exception or at least warn about using it with multiple statements (which would actually mean to detect that which is not exactly trivial).

So, may be, at least a warning in the docu would be appropriate?

I am certainly willing to submit a PR, but I don't think I can/should decide what the correct solution is. I would vote for a warning, if asked.

**Comment by rbt** [comment]
It would be quite tedious to detect multiple queries on the client-side, particularly if a string looks like a query (like creating a plpgsql function).

**Comment by rbt** [comment]
Closing this as I think the current documentation is in reasonable shape. Confusion about perl5's do() intentions should no longer exist as that command has been deprecated in favour of execute().
