### ISSUE TITLE
Spruce up and generally improve Travis

### ISSUE THREAD

**Issue by JJ** [raku-community-modules/DBIish#183]
It's taking 11 minutes per branch, because it's compiling raku every time... Also, it's failing with [some versions and erroring in others](https://travis-ci.org/github/raku-community-modules/DBIish/jobs/691802667). Is it worth the while to keep them?
Maybe it would be convenient to have a set of docker containers, pre-built with mysql and psql (as well as MariaDB, maybe), to test it properly. It would also lead to some improvement if we test different databases separately by using Travis' build matrix.

**Comment by JJ** [comment]
2017.09 is consistently failing now. It should probably be eliminated.

**Comment by rbt** [comment]
Threading in Raku wasn't fully reliable for NativeCalls until 2020.01. DBIish using multiple high-query-rate connections consistently fails on anything lower than that.

**Comment by rbt** [comment]
The older branch shouldn't fail anymore. Threading tests are now skipped on rakudo before 2020.01.

Shorter run-time and Oracle support for travis tests would be nice.

**Comment by rbt** [comment]
Travis is gone.

I setup a Github Action which tests 3 versions of Raku, and several version of Pg and MySQL/MariaDB within about 5 minutes. Much of that time is within zef, probably compiling.
