### ISSUE TITLE
Why can't "do" return rows?

### ISSUE THREAD

**Issue by JJ** [raku-community-modules/DBIish#185]
Aparently, it's just a matter of adding a "return" in the two alternative statements.

https://github.com/raku-community-modules/DBIish/blob/master/lib/DBDish/Connection.pm6#L103-L119

As a matter of fact, it's doing a prepare + execute. 
If it does not, couldn't a multi or another method do that, instead of just returning an error? It does not seem fair to force the user to do a prepare + execute.

**Comment by rbt** [comment]
I'm in favour of changing do to issue the query and return results. Docs can warn about the inefficiencies of preparing a statement multiple times.

There are lots of statements taking parameters will only be issued at a low query rate.

**Comment by rbt** [comment]
In Perl the DBI module avoids prepare/execute for do() statements. They are generally executed directly. It appears to be largely a work-around for drivers which cannot prepare DDL commands.

Raku doesn't have any of those drivers yet and the driver should probably handle it transparently by letting prepare() do different things internally.


Also, both README.pod and examples/*p6 files show `my $sth = $dbh.do(...)`. That's actually incorrect as do does not return a statement handle.
