### ISSUE TITLE
NativeLibs version conflict

### ISSUE THREAD

**Issue by JJ** [raku-community-modules/DBIish#187]
Local version of NativeLibs is 0.0.3, while external version is 0.0.7. This might lead to zef trying to look for it as a dependency. Or something, I'm not really sure what. At any rate, this leads to [this error](https://github.com/salortiz/NativeLibs/issues). I'm not sure of how to solve this. Probably having a single one, and listing it as a reference, is much better.

**Comment by JJ** [comment]
Adding insult to injury, this version is listed as 0.0.3, when it's, in fact, newer than the published version of NativeLibs. 
What I still don't get is why it's automatically created as a dependency if versions are not the same.

**Comment by CurtTilmes** [comment]
There are two distributions in the ecosystem that provide `NativeLibs`:
```
zef info NativeLibs
- Info for: NativeLibs
- Identity: DBIish:ver<0.5.19>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: Yes
Description:     Database connectivity for Perl 6
License:         BSD-2-Clause
Source-url:      git://github.com/perl6/DBIish.git
Provides: 28 modules
Depends: 1 items
```
and
```
zef info 'NativeLibs:ver<0.0.7>:auth<github:salortiz>'
- Info for: NativeLibs:ver<0.0.7>:auth<github:salortiz>
- Identity: NativeLibs:ver<0.0.7>:auth<github:salortiz>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: Yes
Description:     Native libraries utilities
Source-url:      git://github.com/salortiz/NativeLibs.git
Provides: 1 modules
Support:
#   source:     https://github.com/salortiz/NativeLibs.git
#   email:      sog@msg.mx
Depends: 0 items
```

If you don't qualify, a simple `use NativeLibs` will get the one in `DBIish` (which has a higher version than the one in the plain `NativeLibs` distribution).

If you want the other, you have qualify more, such as `use NativeLibs:ver<0.0.7>:auth<github:salortiz>`

**Comment by ugexe** [comment]
Generally we think of module resolution without any qualifier (including installed modules) as taking the highest version available, but really its the highest version available from the first repo of `$*REPO.repo-chain` containing any version at all (I probably would have prefered considering all repos, but the current strategy is superior for speed purposes). This means when using `CompUnit::Repository::FileSystem` to test and there are two dependencies depend on MyDependency from different auths you get something like

```
raku -I /mods/MyDependency1 -I /mods/Foo -I /mods/MyDependency2 -I /mods/Bar t/my-test.t
```

and since each one of those `-I` is a separate CURFS any unqualified use of MyDependency will load whatever version is in `/mods/MyDependency1` and never `/mods/MyDependency2`.

Technically zef could work-around this issue by first installing everything into a temporary repo but that is A) a pretty big workflow change and B) just creates a new impediance between already-installed modules and the temporary repo (since again, first $*REPO containing *any* version). The real way to fix this, as @CurtTilmes  mentions, is to use a more qualified name when using modules. For instance DBIish could add an `auth` field to its META6.json and then do

```
- use NativeLibs;
+ use NativeLibs:auth($?DISTRIBUTION.meta<auth>); # :ver($?DISTRIBUTION.meta<version>) etc
```

to ensure it always uses the expected NativeLibs.

**Comment by rbt** [comment]
Removing NativeLibs from DBIish and depending on the other package appears to work.

https://github.com/raku-community-modules/DBIish/compare/rbt.nativelibs-dependency

Tests pass on Linux for MySQL, MariaDB, SQLlite, and PostgreSQL.

**Comment by ugexe** [comment]
Some more context from 2016 -- https://github.com/salortiz/JsonC/issues/2#issuecomment-218021311

**Comment by tbrowder** [comment]
All other things being equal, would it have helped if the NativeLibs module were in CPAN rather than the ecosystem?

**Comment by ugexe** [comment]
> All other things being equal, would it have helped if the NativeLibs module were in CPAN rather than the ecosystem?

Nope.

It’s just inevitable that people will need to qualify their use statements more and more as time goes on.

**Comment by tbrowder** [comment]
Nick, I think @JJ is working on some module best practice stuff and your advice above sounds like something important to be in there. Some questions, please:

+ Why did you comment out the <ver>? Is it just not needed in this case? 
+ What would be the effect if you used the same syntax for all the legal adverbs for a module without investigating what is actually being used?

**Comment by JJ** [comment]
This is what @tbrowder is talking about Raku/problem-solving#72
I'd be grateful if whoever can do it, would check it out and suggest changes and/or approve.

**Comment by ugexe** [comment]
> Why did you comment out the <ver>? Is it just not needed in this case?

It is not needed in this case. The comment is there to show how one could add the additional constraints based on META6.json if they wanted.

> What would be the effect if you used the same syntax for all the legal adverbs for a module without investigating what is actually being used?

I don't understand this question

**Comment by JJ** [comment]
I don't know if eliminating this version completely will do the trick.
There's a good amount of differences:

```
➜  NativeLibs git:(master) diff lib/NativeLibs.pm6
../DBIish/lib/NativeLibs.pm6
3,11c3,4
< use NativeCall;
< sub EXPORT(|) {
<     my $exp = &trait_mod:<is>.candidates.first: { .signature ~~
:(Routine, :$native!) };
<     Map.new(
<         'NativeCall' => NativeCall,
<         '&trait_mod:<is>' => $exp.dispatcher
<     )
< }
< unit module NativeLibs:auth<salortiz>:ver<0.0.7>;
---
> unit module NativeLibs:auth<sortiz>:ver<0.0.8>;
> use NativeCall :ALL;
30,31c23
<     # This is an HLL clone of MoarVM's loadlib, freelib, et.al. ops.
<     # not available in rakudo.
---
>     # Right now NC::cglobal unload loaded libraries too fast, so we need
our own loader
34,35c26
<     my  %Libraries;
<     my  \dyncall = $*VM.config<nativecall_backend> eq 'dyncall';
---
>     my \dyncall = $*VM.config<nativecall_backend> eq 'dyncall';
40,41c31,32
<     sub dlerror(--> Str)         is native { * } # For linux or darwin/OS
X
<     sub GetLastError(--> uint32) is native('kernel32') { * } # On
Microsoft land
---
>     my sub dlerror(--> Str)         is native { * } # For linux or
darwin/OS X
>     my sub GetLastError(--> uint32) is native('kernel32') { * } # On
Microsoft land
43c34,41
<         is-win ?? ( dlerror() // '' ) !! "error({ GetLastError })";
---
> given $*VM.config<osname>.lc {
>    when 'linux' | 'darwin' {
> dlerror() // '';
>    }
>    when 'mswin32' | 'mingw' | 'msys' | 'cygwin' {
> "error({ GetLastError })";
>    }
> }
46,48c44,46
<     sub dlLoadLibrary(Str --> DLLib)  is native { * } # dyncall
<     sub dlopen(Str, uint32 --> DLLib) is native { * } # libffi
<     sub LoadLibraryA(Str --> DLLib) is native('kernel32') { * }
---
>     my sub dlLoadLibrary(Str --> DLLib)  is native { * } # dyncall
>     my sub dlopen(Str, uint32 --> DLLib) is native { * } # libffi
>     my sub LoadLibraryA(Str --> DLLib) is native('kernel32') { * }
50c48
< is-win  ?? LoadLibraryA($libname) !!
---
>         is-win  ?? LoadLibraryA($libname) !!
60,81c58
<    fail "Cannot load native library '$libname'";
< }
<     }
<
<     sub dlFindSymbol(  DLLib, Str --> Pointer) is native { * } # dyncall
<     sub dlsym(         DLLib, Str --> Pointer) is native { * } # libffi
<     sub GetProcAddress(DLLib, Str --> Pointer) is native('kernel32') { * }
<     sub GetModuleHandleA(     Str -->   DLLib) is native('kernel32') { * }
<     method symbol(::?CLASS $self: Str $symbol, Mu $want = Pointer) {
< my \c = \(
<             $self.DEFINITE ?? $!library !!
<             is-win ?? GetModuleHandleA(Str) !! DLLib,
<             $symbol
<         );
< my \ptr = (
<             is-win ?? &GetProcAddress !! dyncall ?? &dlFindSymbol !!
&dlsym
<         )(|c);
<
< if ptr && $want !=== Pointer {
<    nativecast($want, ptr);
< } else {
<    ptr
---
>    fail "Cannot load native library '$libname'" ~ self!dlerror();
85,88c62,63
<     sub dlFreeLibrary(DLLib) is native { * }
<     sub dlclose(      DLLib) is native { * }
<     sub FreeLibrary(  DLLib --> int32) is native('kernel32') { * }
<     method dispose(--> True) {
---
>     sub dlFreeLibrary(DLLib) is native { * };
>     method dispose {
90,91c65
<             is-win  ?? FreeLibrary($_) !!
<    dyncall ?? dlFreeLibrary($_) !!  dlclose($_);
---
>    dlFreeLibrary($_);
98c72
<     method !test($try, $wks) {
---
>     method !test(Str() $try, $wks) {
102a77
> return $wlibname unless $libname; # Nothing to test
104c79
<    my $version = $_.defined ?? Version.new($_) !! Version;
---
>    my $ver = $_.defined ?? Version.new($_) !! Version;
106c81
< cannon-name($libname, $version), $wks;
---
> cannon-name($libname, $ver), $wks;
111c86
< $wlibname //= self!test: "lib$libname.dll", $wks if is-win;
---
> $wlibname //= self!test: "lib$libname.dll", $wks;
114d88
<
123c97
< #die "Cannot locate native library '$libname'"
---
> # die "Cannot locate native library '$libname'"
129,156d102
<
< class Compile {
<     has @.files;
<     has $.name;
<     has $.lib;
<     has $.outdir;
<
<     my $cfg = $*VM.config;
<     submethod BUILD(:$!name!, :$!outdir, :@!files) {
<         @!files.push: $!name unless @!files;
<         $!lib = $*VM.platform-library-name($!name.IO);
<         $_ .= subst(/\.c$/,'') for @!files;
<     }
<
<     method compile-file($file is copy) {
<         my $CC = "$cfg<cc> -c $cfg<ccshared> $cfg<cflags>";
<         my $c-line = join(' ', $CC, "$cfg<ccout>$file$cfg<obj>",
"$file.c");
<         shell($c-line);
<     }
<
<     method compile-all {
<         self.compile-file($_) for @!files;
<         my $LD = "$cfg<ld> $cfg<ldshared> $cfg<ldflags> $cfg<ldlibs>";
<         my $l-line = join(' ', $LD, "$cfg<ldout>$!lib", @!files.map(* ~
$cfg<obj>));
<         shell($l-line);
<     }
< }
<
161d106

-- 
JJ

**Comment by JJ** [comment]
I think that for the time being the best way to solve the conflict is simply give it different names.

**Comment by tbrowder** [comment]
> > What would be the effect if you used the same syntax for all the legal adverbs for a module without investigating what is actually being used?
> 
> I don't understand this question

Should I (or could I) as a module author publishing public modules use, as a general practice, your recommendation from above and generalize it, e.g.,

```
use Foo:auth($DISTRIBUTION.meta<auth>):ver($DISTRIBUTION.meta<version>):api($DISTRIBUTION.meta<api>);
```
unless we have a special need to be more specific.  Wouldn't that take care of the current problem even if it is using more constraints?

**Comment by ugexe** [comment]
Generally yes, that is what most people want. Note though that on windows this only works on releases after 2020.01 -- https://github.com/rakudo/rakudo/commit/13c5d04622e2242f51cf06eec97fa54056e67c97

**Comment by tbrowder** [comment]
Great! I'll try to start doing that. Thanks.

**Comment by rbt** [comment]
Is this resolved sufficiently? Can we close it?

**Comment by JJ** [comment]
I think so, yes.

**Comment by salortiz** [comment]
The `NativeLib` included in DBDIsh is _newer_ than the external one only because I back-ported from the former the `cannon-name` sub in https://github.com/raku-community-modules/DBIish/commit/241b7d4c93ef07d613bf704f902b5846e155d888. ( @rbt change some indentation in https://github.com/raku-community-modules/DBIish/commit/0d325159763606e81b29577d4a19d5c3203a0ec8)

And the only reason for not removing it from `DBDIsh` and using the external was, at that time, to avoid introducing in `Rakudo Star` another dependency. 

When the external (grow-up) `NativeLib` was originally released, I deliberately give it a gap in its version number, so projects requiring the extended/expanded functionality can request it by an explicit  `"depends" : [ "NativeLibs:ver<0.0.6+>" ]` in its META6.json.

So, @JJ 's https://github.com/raku-community-modules/DBIish/commit/ec857b4395b0cc0cb4629d2079fde82da3ed1add commit is a really bad idea.

I think that removing from `DBDIsh` the striped down `NativeLibs` should work without problems.

**Comment by JJ** [comment]
@salortiz it's simply locking a specific version; @ugexe's idea of using the distribution version is very probably a better idea. I didn't want to remove a large chunk of code (and introducing another dependency on the process). I mean, at the end of the day, using the same name in two different (although related) pieces of code is bound to create name clashes. I'll reopen anyway and see if we can come together to a best solution (or, even better, PR)

**Comment by softmoth** [comment]
> I didn't want to remove a large chunk of code

The diff you posted on Jun 2 shows that there are no real changes. That's all extra features in the real distribution, so it is totally fine to remove it from DBIish and as the dependency, IMO.
