### ISSUE TITLE
running the examples doens't work

### ISSUE THREAD

**Issue by dataf3l** [raku-community-modules/DBIish#195]
I tried the sqlite example, and got this error:

No such method 'execute' for invocant of type 'DBDish::SQLite::Connection'
  in block <unit> at db1.p6 line 14

This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

What should I do?

**Comment by rbt** [comment]
Is your DBIish up to date?

zef uninstall DBIish
zef install DBIish

**Comment by rbt** [comment]
Pretty sure the DBIish installed was out of date.

Please reopen if that was not the case.
