### ISSUE TITLE
Can't query mysql table with dateTime unless using prepared statement

### ISSUE THREAD

**Issue by Digicrat** [raku-community-modules/DBIish#196]
If I query any MySQL table with a "datetime" column directly (ie: $dbh.execute($query), I get the exception below.  The error occurs even if the datetime column is not selected, but does not occur for other tables.

It consistently hits this error when calling the ".rows()" or ".allrows()" methods to get the actual results.  

If I convert the same query to the prepared format ($sth=$dbh.prepare($query), $sth.execute()), then it works correctly.

This is with moar-2020.01 and a freshly installed DBIish.

```
Cannot find method 'DateTime' on object of type Str
  in method want at ...[removed for brevity]... (DBDish::mysql::Native) line 117
  in code  at ... (DBDish::mysql::StatementHandle) line 216
  in method _row at ... (DBDish::mysql::StatementHandle) line 216
  in method row at ...(DBDish::StatementHandle) line 91
  in block  at ... (DBDish::StatementHandle) line 130
  in block <unit> at ./sql_test.pl6 line 36
```

**Comment by rbt** [comment]
The MySQL driver has a special case for $dbh.execute without parameters so special queries like LOCK TABLE don't throw an error. This path goes through an entirely different protocol for DB communication which does type handling differently from the prepared version.

I'll try to fix it but it might take some time.

Thank-you for the report.
