### ISSUE TITLE
Add support to firebird database

### ISSUE THREAD

**Issue by demanuel** [raku-community-modules/DBIish#217]
Is it possible to add support to firebird database?

URL: https://firebirdsql.org/

Firebird is an opensource database that can be used as an embedded database. It used to be big in the delphi community.

**Comment by jonathanstowe** [comment]
It would be good to support as many DBMS as possible *but* there is no particular reason that it needs to be part of this module; it could be added to teh ecosystem separately like e.g. [DBDish::ODBC[(https://github.com/salortiz/DBDish-ODBC), which might be preferable as it can be maintained separately by someone who knows Firebird in detail and can move at its own pace.

BTW there is a Firebird ODBC driver available, so almost certainly it could be made to work with DBDish::ODBC.

**Comment by demanuel** [comment]
@jonathanstowe Thanks for the reply.

If it's supported with DBDish::ODBC, will i also be able to use it with DBIish?

**Comment by jonathanstowe** [comment]
Yes, that's exactly the point.  The `DBDIsh` modules are the "_driver_" part and should just work like the "built-in" ones.

**Comment by demanuel** [comment]
Thanks, i will close this.
