### ISSUE TITLE
Cryptic error message on using disconnect

### ISSUE THREAD

**Issue by grizzlysmit** [raku-community-modules/DBIish#232]
Hi I get the following message when I use $dbh.disconnect:

```sh
$ ./t.raku
Saw 1 occurrence of deprecated code.
================================================================================
Method protect (from Lock) seen at:
  SETTING::src/core.c/Rakudo/Internals.pm6, line 1780
Please use dispose instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
```

caused by 

```raku
method disconnect is hidden-from-backtrace is DEPRECATED("dispose") {
    self.dispose;
}
```

in DBDish::Connection 

need a better error message something that mentions the diconnect call would help my boiled down code is:

```raku
#!/usr/bin/env raku
use DBIish;

my $database = 'urls';
my $user     = 'urluser';
my $password = '*******************';

my $dbh = DBIish.connect('Pg', :host<rakbat.local>, :port(5432), :$database, :$user, :$password);

END {
    $dbh.disconnect();
}
```

password elided 
took me a long time to find in my original code.

**Comment by rbt** [comment]
I see. It's because we combined `is hidden-from-backtrace` with `is DEPRECATED("dispose")`. This causes the deprecation report to pickup the incorrect line.

I've reported it upstream here:
https://github.com/rakudo/rakudo/issues/5055

**Comment by rbt** [comment]
Deprecated code will be removed from DBIish shortly. They've been marked that way for 2 years, which is a fairly long time for Raku.
