### ISSUE TITLE
the pod is not cool

### ISSUE THREAD

**Issue by jdv** [raku-community-modules/DBIish#39]
1.  README.pod is p5 pod so invalid.
2.  The pod in the code files is malformatted by way of
   lacking space between pod directives and content.

**Comment by Skarsnik** [comment]
Yes DBIish pod (documentation) is rather weird/lacking.

I suspect the Readme.pod is pod5 so github can display it. It's probably not a real issue. But moving this to DBIish.pm and probably generate the readme from it could be a nice solution.

**Comment by abraxxa** [comment]
I had a hard time finding docs on Perl 6 pod when I started to add docs to DBDish::Oracle.

**Comment by JJ** [comment]
We should probably export it to markdown...

**Comment by rbt** [comment]
Is there a consensus to change to markdown?

If so, I'll volunteer to do the work.

**Comment by jonathanstowe** [comment]
Yes, it should be markdown,
