### ISSUE TITLE
MySQL: longblob always allocates 4GB of memory

### ISSUE THREAD

**Issue by Demayl** [raku-community-modules/DBIish#74]
It's not so practical to allocate max blob size into Buf when selecting a row from mysql.

**Comment by samgwise** [comment]
This also appears to happen JSON types:
`MoarVM panic: Memory allocation failed; could not allocate 4294967295 bytes`

I worked around this by casting to a CHAR type with a set max size, explained here: [MySQL Manual - 12.10 Cast Functions and Operators](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html)

It may be possible to do the same for longblobs but as binary instead.

**Comment by rbt** [comment]
7531549c2be658 should have fixed the over-allocation.

The buffer is resized to the longest provided string or blob. It could be more efficient, but it shouldn't fail unless the actual tuple is very large.
