### ISSUE TITLE
MySQL "0" timestamps mishandled.

### ISSUE THREAD

**Issue by lucs** [raku-community-modules/DBIish#75]
The following will give the error "Month out of range. Is: 0, should be in 1..12".

#!/usr/bin/env perl6

=begin doc

Have a database with a table having a timestamp column, and add a
record where that timestamp is zero:

    create database test_db;
    use test_db;
    create table test_table (my_timestamp timestamp);
    insert into test_table (my_timestamp) values (0);

=end doc

use DBIish;

sub MAIN {
    my $user = 'whomever';
    my $password = 'PaSsWoRd';
    my $db-name = 'test_db';
    my $table-name = 'test_table';

    my $dbh = DBIish.connect('mysql', database => $db-name, :$user, :$password);
    my $sth = $dbh.prepare('select * from test_table');
    $sth.execute;
    $sth.fetchall_arrayref;
}

**Comment by Demayl** [comment]
Same error for datetime field with value '0000-00-00 00:00:00'

**Comment by rbt** [comment]
The Raku DateTime type doesn't accept values which did not exist; simply put, Raku is more strict than MySQL in this regard.

DBIish could fallback to providing a String of the value instead of a DateTime object. Is that desirable?

**Comment by jonathanstowe** [comment]
> DBIish could fallback to providing a String of the value instead of a DateTime object. Is that desirable?

I think in terms of Rakuish expectations, it would be return a DateTime type object - MySQL means NULL when it puts those values in timestamp and datetime columns.

**Comment by rbt** [comment]
> I think in terms of Rakuish expectations, it would be return a DateTime type object - MySQL means NULL when it puts those values in timestamp and datetime columns.

That's trivial to implement. A round-trip would change the DB value to a NULL, which seems to be the recommended solution for these legacy timestamps.

It appears NO_ZERO_DATE has been the default since 2015 with MySQL 5.7. Is this still a problem DBIish needs to be concerned about?

**Comment by jonathanstowe** [comment]
Seven years is a short time in DB years, there will be plenty of data out there like that. Whether it will pass through DBIish is another matter.

**Comment by rbt** [comment]
Note, I did not handle zeros in other parts of the date, such as 1999-12-00.

**Comment by jonathanstowe** [comment]
> I did not handle zeros in for a portion of the date

I would hope that MySQL would reject them as invalid long before they got near the actual DB.

**Comment by rbt** [comment]
> I would hope that MySQL would reject them as invalid long before they got near the actual DB.

Versions prior to 5.7 allowed them, or even new versions with strict date checking disabled, but it also wouldn't auto-create dates like that so I doubt they're as common.
