### ISSUE TITLE
MySQL does not pass Num/Rat correctly

### ISSUE THREAD

**Issue by bbkr** [raku-community-modules/DBIish#76]
Proof is a bit tricky, because MySQL does not allow to explicitly get variable type that it got from driver. So I'll use a bit of nasty overflows and implicit casts to illustrate this. 

```perl6
my $sth = $dbh.prepare(q{SELECT 14655374668259132385 % ?});
```

**Integer binding**

```
mysql> SELECT 14655374668259132385 % 2;
+--------------------------+
| 14655374668259132385 % 2 |
+--------------------------+
|                        1 |
+--------------------------+
1 row in set (0.00 sec)
```

```perl6
$sth.execute(2);
dd $sth.fetchall_arrayref();

# prints [["1"],]
```

So integers are OK.

**String binding**

```
mysql> SELECT 14655374668259132385 % '2';
+----------------------------+
| 14655374668259132385 % '2' |
+----------------------------+
|                          0 |
+----------------------------+
1 row in set (0.01 sec)
```

```perl6
$sth.execute("2");
dd $sth.fetchall_arrayref();

# prints [["0"],]
```

And this is also OK, despite stupid result.
String was passed and implicitly casted by server to Double and overflows in consistent way with console.

**Num binding**

```
mysql> SELECT 14655374668259132385 % 2.0;
+----------------------------+
| 14655374668259132385 % 2.0 |
+----------------------------+
|                        1.0 |
+----------------------------+
1 row in set (0.00 sec)
```

```perl6
$sth.execute(2.0.Num);
dd $sth.fetchall_arrayref();

# prints [["0"],]
```

Which is incorrect. That means Nums are stringified somewhere along the way?

Expected output is the one consistent with console.

**Comment by bbkr** [comment]
Easier way to see what server gets is to do

```perl6
my $sth = $dbh.prepare('CREATE TABLE tmp_test AS SELECT ?');
$sth.execute(2.0);
```

Table indeed has string-y column

```
mysql> show create table tmp_test\G
*************************** 1. row ***************************
       Table: tmp_test
Create Table: CREATE TABLE `tmp_test` (
  `?` varchar(1) NOT NULL DEFAULT ''     <==== incorrect, should be decimal
) ENGINE=InnoDB DEFAULT CHARSET=utf8
1 row in set (0.00 sec)
```

I'm not sure if this is libmysqlclient limitation or decision to pass P6 Nums as strings, but this will give weird results due to implicit conversions to double if not explicitly casted in query.

**Comment by Skarsnik** [comment]
All the fetch* method will return everything to a string form. Did you try with the recomanded API?(row/allrows)

**Comment by bbkr** [comment]
It's not about returned valued being strings.
The issue is that about incorrect passing Num values from DBIish to server.

**Comment by astj** [comment]
Maybe this is due to DBDish::mysql::StatementHandle's binding logic?
ref: https://github.com/perl6/DBIish/blob/1bb0d44287bb3eb9b7ab6e3e09d93ffb15313fde/lib/DBDish/mysql/StatementHandle.pm6#L100-L110

**Comment by rbt** [comment]
[This commit](https://github.com/raku-community-modules/DBIish/commit/5a76c80e113daffaeb6ba0b66f2ac20736a64aee) works for basic stuff.

I'm uncertain how to detect when a value doesn't fit into a num64. It just becomes an incorrect value rather than an error and a max/min value range doesn't prevent loss of precision.
